#!/bin/bash

##SYSTEM WIDE

mkdir -p /etc/X11/xorg.conf.d
/usr/sbin/groupadd firefox

TMP_DIR=$(mktemp -d)

FIREFOX_DOWNLOAD_PATH="$TMP_DIR/firefox.tar.bz2"




echo "Setting default keyboard to \"us altgr-intl\" (/etc/X11/xorg.conf.d/00keyboard.conf)"
wget 'https://gist.githubusercontent.com/Cheloide/523157f3de0b9e4e7599b090c8886c18/raw/00keyboard.conf' -O "/etc/X11/xorg.conf.d/00keyboard.conf"

echo installing Latest version of Ulauncher
LATEST_ULAUNCHER_URL=`curl --silent "https://api.github.com/repos/Ulauncher/Ulauncher/releases/latest" | grep -E "browser_download_url.*?\.deb\"" | sed -E 's/.*"([^"]+)".*/\1/'`
wget "$LATEST_ULAUNCHER_URL" -O $TMP_DIR/ulauncher.deb
apt install "$TMP_DIR/ulauncher.deb" -y


wget 'https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US' -O "$FIREFOX_DOWNLOAD_PATH"

tar -xvjf "$FIREFOX_DOWNLOAD_PATH" -C /opt
chown -R nobody:firefox /opt/firefox
chmod -R u=g /opt/firefox/

update-alternatives --install /usr/bin/firefox firefox /opt/firefox/firefox 1000
update-alternatives --install /usr/bin/x-www-browser x-www-browser /opt/firefox/firefox 1000
update-alternatives --install /usr/bin/gnome-www-browser gnome-www-browser /opt/firefox/firefox 1000
update-alternatives  --set firefox /opt/firefox/firefox
update-alternatives  --set x-www-browser /opt/firefox/firefox
update-alternatives  --set gnome-www-browser /opt/firefox/firefox

##USER SPECIFIC

function create_autostart {

    USERNAME=$1
    NAME=$2
    EXEC=$3

    runuser $USERNAME -l -c "mkdir -p ~/.config/autostart/"
    runuser $USERNAME -l -c "printf \"[Desktop Entry]\nEncoding=UTF-8\nType=Application\nName=%s\nExec=%s\nTerminal=false\" \"$NAME\" \"$EXEC\" | tee \"\$HOME/.config/autostart/$NAME.desktop\""

}


while [ -z $USERNAME_EXISTS ] || [ $USERNAME_EXISTS != 0 ];
do
    
    read -p "Input the username to setup, leave blank to skip: " USERNAME

    if [ -z "$USERNAME" ]; then
        echo "Nothing more to do... exiting."
        exit 0
    fi
    
    getent passwd "$USERNAME" > /dev/null
    USERNAME_EXISTS=$?

    if [ $USERNAME_EXISTS != 0 ]; then
        echo "Invalid Username."
    fi
done

runuser $USERNAME -l -c "mkdir -p ~/.config/autostart"
runuser $USERNAME -l -c "mkdir -p ~/.config/openbox"

create_autostart "$USERNAME" 'compton'     'compton'
create_autostart "$USERNAME" 'tint2'        'tint2'
create_autostart "$USERNAME" 'steam'        'steam -silent'
create_autostart "$USERNAME" 'zim'          'zim --plugin trayicon'
create_autostart "$USERNAME" 'feh'          'bash -c "feh --bg-scale /home/$USER/.wallpapers/$(ls /home/$USER/.wallpapers |sort -R |tail --lines=1 )'
create_autostart "$USERNAME" 'flameshot'    'flameshot'
create_autostart "$USERNAME" 'guake'        'guake'
create_autostart "$USERNAME" 'deluge-gtk'   'deluge-gtk'
create_autostart "$USERNAME" 'copyq'        'copyq'
create_autostart "$USERNAME" 'numlockx'     'numlockx on'
create_autostart "$USERNAME" 'nosleep'      'xset -dpms s off'
create_autostart "$USERNAME" 'ulauncher'    'xset -dpms s off'
 


runuser $USERNAME -l -c "wget https://gist.github.com/Cheloide/6779daeed158c2b228ea857f53eeb2bb/raw/rc.xml -O /home/$USERNAME/.config/openbox/rc.xml"

read -p "set $USERNAME as superuser (y/n, default: Yes)" SUPERUSER

 if [ -z "${SUPERUSER}" ] || [ "${SUPERUSER,,}" = "y" ] || [ "${SUPERUSER,,}" = "yes" ]; then
    echo "Executing \"/sbin/usermod -aG sudo $USERNAME\""
    /sbin/usermod -aG sudo $USERNAME
 else
    echo "Skipping superuser configuration for user $USERNAME"
 fi

/sbin/usermod -aG firefox $USERNAME
